### ISSUE TITLE
Inertia modal is displaying instead of navigating to the route

### ISSUE THREAD

**Issue by jamgar** [jamgar/test-inertia#2]
When I click on the Sign in link on the root_path it display a modal with the login form instead of navigating to the sign in route
<img width="501" alt="Screen Shot 2020-08-25 at 6 20 33 PM" src="https://user-images.githubusercontent.com/14931684/91237268-c4248c80-e6ff-11ea-877a-d910340044a7.png">

If I change the inertia-link to an anchor tag it works as expected, but would rather use inertia-link. I disabled Turbolinks thinking it may have something to do with it, but that did not change the result.

**Comment by jamgar** [comment]
Response from Inertia creator:
Okay, so a couple things.
1. Inertia and Turbolinks are not compatible. You'll have to pick one or the other.
2. When you login, and a redirect happens server-side, you need to make sure that the page you land on is an Inertia page, otherwise you'll get a modal with your page content (essentially an error).
All Inertia requests must receive Inertia responses, otherwise a modal is shown.
You might find this example Inertia app on Rails helpful: https://github.com/ledermann/pingcrm

**Comment by ledermann** [comment]
As @reinink (the Inertia.js creator) already said, the resulting page must be an Inertia page - which is not the case here. The login form in your application comes from Devise and is a plain old HTML page, which is not the right response for an Inertia request. You should rebuild the login form as a Vue template instead. Here are some links to the relevant parts of the PingCRM demo application for Rails which does this thing:

* https://github.com/ledermann/pingcrm/blob/master/app/controllers/users/sessions_controller.rb#L3-L5
* https://github.com/ledermann/pingcrm/blob/master/app/javascript/Pages/Auth/Login.vue

In addition, you should remove all the TurboLinks stuff from your application, especially using the `turbolinks:load` event to initialize Vue seems not right to me. 

If you want to migrate an existing app to Inertia step by step, you can use separate layout templates (eg. `application.html.erb` and `application-inertia.html.erb`) and/or JS entry points (e.g. `application.js` and `application-inertia.js`) for controllers you have already inertia-lized.

**Comment by jamgar** [comment]
@ledermann Thank you for the information. This is very helpful. It looks like you have the gist of what I was trying to do. I am trying to figure this all out so I can write a proper blog about using Inertia with an existing Rails app, which may include developers using Turbolinks and are not able to disable it while they are moving to Inertia. I will definitely credit you in the blog if I every get it done 😆

**Comment by ledermann** [comment]
Great, I'm looking forward to your blog post :-)
